[package]
name = "waffle_graph"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
log = "0.4.25"
priority-queue = "2.1.1"
rustc-hash = "2.1.0"
simple-error = "0.3.1"
thiserror = "2.0.11"
